package draft

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"path"
	"sort"

	"github.com/ontopix/engram/internal/documentprofile"
	"github.com/ontopix/engram/internal/snapshot"
)

type catalogAddition struct {
	path        string
	description string
	pinned      bool
}

// planCatalog regenerates one existing, structurally valid catalog region.
// It records exact captures for the README, its direct entry set, and every
// child frontmatter source used to derive the generated bytes.
func (p *planner) planCatalog(directory string, addition *catalogAddition) (logicalPath string, updated []byte, changed bool, err error) {
	return p.planCatalogMutation(directory, "", addition)
}

// planCatalogMutation regenerates a catalog against one prospective direct
// record removal and/or addition. The empty removal means no removal.
func (p *planner) planCatalogMutation(directory, removal string, addition *catalogAddition) (logicalPath string, updated []byte, changed bool, err error) {
	logicalPath = joinLogical(directory, "README.md")
	file, exists := p.checked.Tree.Files[logicalPath]
	if !exists || file.Role != snapshot.RoleMap {
		return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, logicalPath, errors.New("content directory has no regular README.md"))
	}
	directoryMap := p.checked.Maps[logicalPath]
	if directoryMap == nil {
		return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, logicalPath, errors.New("README frontmatter is unavailable"))
	}
	mode := documentprofile.CatalogMode(directoryMap.Catalog)
	if !documentprofile.ValidCatalogMode(mode) {
		return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, logicalPath, errors.New("README catalog mode is invalid"))
	}
	document, parseErr := documentprofile.Parse(file.Data)
	if parseErr != nil {
		return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, logicalPath, parseErr)
	}
	detection := documentprofile.DetectCatalog(document.BodyBytes())
	if !detection.ValidForMode(mode) {
		return logicalPath, nil, false, typed(ErrorConflict, p.plan.operation, logicalPath, documentprofile.ErrCatalogMarkerShape)
	}
	if _, captureErr := p.captureDirectory(directory); captureErr != nil {
		return logicalPath, nil, false, captureErr
	}
	if _, captureErr := p.captureFile(logicalPath, file.Data); captureErr != nil {
		return logicalPath, nil, false, captureErr
	}
	if mode == documentprofile.CatalogNone {
		return logicalPath, append([]byte(nil), file.Data...), false, nil
	}

	directories := make([]documentprofile.CatalogDirectory, 0)
	for _, child := range p.checked.Tree.Directories {
		if child == directory || parentLogical(child) != directory {
			continue
		}
		childMapPath := joinLogical(child, "README.md")
		childFile, exists := p.checked.Tree.Files[childMapPath]
		childMap := p.checked.Maps[childMapPath]
		if !exists || childFile.Role != snapshot.RoleMap || childMap == nil || childMap.Description == nil {
			return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, childMapPath, errors.New("child directory description is unavailable"))
		}
		if _, captureErr := p.captureFile(childMapPath, childFile.Data); captureErr != nil {
			return logicalPath, nil, false, captureErr
		}
		directories = append(directories, documentprofile.CatalogDirectory{
			Name: path.Base(child), Description: *childMap.Description,
		})
	}

	records := make([]documentprofile.CatalogRecord, 0)
	if mode == documentprofile.CatalogAll {
		for _, recordPath := range treeFilePaths(p.checked.Tree, snapshot.RoleRecord, directory) {
			if recordPath == removal {
				continue
			}
			childFile := p.checked.Tree.Files[recordPath]
			record := p.checked.Records[recordPath]
			if record == nil || record.Description == nil || !record.PinnedValid {
				return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, recordPath, errors.New("record catalog metadata is unavailable"))
			}
			if _, captureErr := p.captureFile(recordPath, childFile.Data); captureErr != nil {
				return logicalPath, nil, false, captureErr
			}
			records = append(records, documentprofile.CatalogRecord{
				Name: path.Base(recordPath), Description: *record.Description, Pinned: record.Pinned,
			})
		}
		if addition != nil {
			records = append(records, documentprofile.CatalogRecord{
				Name: path.Base(addition.path), Description: addition.description, Pinned: addition.pinned,
			})
		}
	}
	generated, generateErr := documentprofile.GenerateCatalog(mode, directories, records)
	if generateErr != nil {
		return logicalPath, nil, false, typed(ErrorRepository, p.plan.operation, logicalPath, generateErr)
	}
	body, bodyChanged, replaceErr := documentprofile.ReplaceCatalog(document.BodyBytes(), generated)
	if replaceErr != nil {
		return logicalPath, nil, false, typed(ErrorConflict, p.plan.operation, logicalPath, replaceErr)
	}
	if !bodyChanged {
		return logicalPath, append([]byte(nil), file.Data...), false, nil
	}
	updated = make([]byte, 0, document.Body.Start+len(body))
	updated = append(updated, file.Data[:document.Body.Start]...)
	updated = append(updated, body...)
	return logicalPath, updated, !bytes.Equal(updated, file.Data), nil
}

// PlanFmt computes exact catalog-only edits without publishing them.
func PlanFmt(ctx context.Context, root string, options FmtOptions) (*Plan, FmtResult, error) {
	const operation = "fmt"
	p, err := openPlanner(ctx, operation, root)
	if err != nil {
		return nil, FmtResult{}, err
	}
	defer p.close()

	selected, err := selectReadmes(p.checked.Tree.Directories, options.Paths)
	if err != nil {
		return nil, FmtResult{}, typed(ErrorUsage, operation, "", err)
	}
	changedPaths := make([]string, 0, len(selected))
	for _, readme := range selected {
		if err := cancelled(ctx, operation); err != nil {
			return nil, FmtResult{}, err
		}
		directory := parentLogical(readme)
		logicalPath, content, changed, err := p.planCatalog(directory, nil)
		if err != nil {
			return nil, FmtResult{}, err
		}
		if !changed {
			continue
		}
		before := p.plan.captures[logicalPath]
		p.addFile(logicalPath, before, content, directory)
		changedPaths = append(changedPaths, logicalPath)
	}
	sort.Slice(changedPaths, func(i, j int) bool {
		return bytes.Compare([]byte(changedPaths[i]), []byte(changedPaths[j])) < 0
	})
	result := FmtResult{
		DryRun: options.DryRun, Check: options.Check,
		Changed: len(changedPaths) != 0, Paths: changedPaths,
	}
	return p.plan, result, nil
}

// Fmt plans and, unless --check or --dry-run semantics were requested,
// publishes catalog-only updates.
func Fmt(ctx context.Context, root string, options FmtOptions) (FmtResult, error) {
	plan, result, err := PlanFmt(ctx, root, options)
	if err != nil {
		return FmtResult{}, err
	}
	if options.Check || options.DryRun || !result.Changed {
		return result, nil
	}
	if err := plan.PublishWith(ctx, options.Rendezvous); err != nil {
		return FmtResult{}, err
	}
	return result, nil
}

// Format is a readable alias for Fmt for library callers.
func Format(ctx context.Context, root string, options FmtOptions) (FmtResult, error) {
	return Fmt(ctx, root, options)
}

// PlanFormat is a readable alias for PlanFmt for library callers.
func PlanFormat(ctx context.Context, root string, options FmtOptions) (*Plan, FmtResult, error) {
	return PlanFmt(ctx, root, options)
}

func selectReadmes(directories, selections []string) ([]string, error) {
	selected := make(map[string]struct{})
	if len(selections) == 0 {
		for _, directory := range directories {
			selected[joinLogical(directory, "README.md")] = struct{}{}
		}
		return sortedStrings(selected), nil
	}
	for _, selection := range selections {
		if selection == "" {
			return nil, errors.New("fmt path must not be empty")
		}
		if selection == "README.md" || path.Base(selection) == "README.md" {
			if path.Clean(selection) != selection || selection[0] == '/' || bytes.ContainsRune([]byte(selection), '\\') {
				return nil, fmt.Errorf("invalid logical README path %q", selection)
			}
			directory := parentLogical(selection)
			if !validLogicalDirectory(directory) || !containsDirectory(directories, directory) {
				return nil, fmt.Errorf("README path %q is not in an existing content directory", selection)
			}
			selected[selection] = struct{}{}
			continue
		}
		if !validLogicalDirectory(selection) || !containsDirectory(directories, normalizeRoot(selection)) {
			return nil, fmt.Errorf("fmt path %q is not an existing content directory or its README", selection)
		}
		selected[joinLogical(normalizeRoot(selection), "README.md")] = struct{}{}
	}
	return sortedStrings(selected), nil
}

func normalizeRoot(value string) string {
	if value == "" || value == "." {
		return "."
	}
	return value
}
